repos:
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       language_version: python3  # Use the Python version managed by Poetry
  #       args: [--ignore-missing-imports]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        language_version: python3  # Use the Python version managed by Poetry
