services:
  backend:
    container_name: tldd-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - SERVICE_ACCOUNT_KEY=$SERVICE_ACCOUNT_KEY
    environment:
      - PORT=8000
      - K_SERVICE=dev
      - K_CONFIGURATION=dev
      - K_REVISION=dev-00001
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8736
    ports:
      - "8000:8000"
